### ISSUE TITLE
SignatureAlgo(alg) is hardcoded as sha256

### ISSUE THREAD

**Issue by Sethide** [Path-Check/icaovds.sdk.js#2]
Signature Algo seems to be hard coded to [sha256](https://github.com/Path-Check/vds-sdk.js/blob/cc77768002a33f3781761f05a1ca8e530eeef5a5/lib/vds.js#L25).

![image](https://user-images.githubusercontent.com/91232812/136376246-cda70822-fdac-4c19-ac4f-4914de71df5c.png)

Is it possible to use the one indicated in the payload instead?
Thank you.
Seth

**Comment by vitorpamplona** [comment]
Yep, I am trying to figure out the best way to get the hash function from the Private key itself, maybe through the EC Params data. 

More to come.

**Comment by vitorpamplona** [comment]
I just released a new version where the hash algorithm is based on the curve type. 

Let me know if this works for you.
